echo Deleting Cluster Role Binding...
kubectl delete clusterrolebinding tiller-clusterrolebinding

echo Creating Cluster Role Binding...
kubectl create -f rbac-config.yaml

echo Deleting tiller...
kubectl delete deploy tiller-deploy --namespace=kube-system

echo Upgrading tiller...
helm init --upgrade 